### ISSUE TITLE
Set up this repo with graphite

### ISSUE THREAD

**Issue by arduano** [urbas/rix#123]
Hey @urbas, I've been trying to get this repository working with Graphite, but it seems to require adding the graphite app to this repository or something (or maybe to your account, not sure). Would you please be able to set it up with your account?

Main reason I want to use graphite is it will let me queue up like 10 small PRs for you to review instead of 1 big one, so I can do more work without leaving you with one massive review

**Comment by urbas** [comment]
I must admit I don't quite understand. I would expect you already have enough permissions to set up graphite for yourself (as you are able to create PRs, review them, and merge them). If that's not enough for graphite, then we'd have to research what's going on here (what and why graphite needs) and understand it better before activating it.

Apologies for being difficult here, but in light of the recent events (see [this post by the oss foundation](https://openssf.org/blog/2024/04/15/open-source-security-openssf-and-openjs-foundations-issue-alert-for-social-engineering-takeovers-of-open-source-projects/)) we have to be extra mindful.

**Comment by arduano** [comment]
Graphite runs as an app that automatically manages pull requests on your behalf. It is a way of automatically stacking small pull requests that are easier to review, without dealing with merge conflicts, and automatically rebasing all stacked pull requests when any change on a lower PR is made.

For some reason, graphite complains that it doesn't have access to this repository when I try to submit a stack of PRs. I've added a personal access token to graphite already, but I think it's testing based on username ownership.

In terms of security, I've used graphite at one of my nonprofit jobs (until they removed the nonprofit plan), but it seems to be free for OSS projects still.

If you're not comfortable with adding something like this, that's ok, I can figure out how to do it manually outside graphite, which could be an interesting challenge on its own, but yeah.

**Comment by arduano** [comment]
I'm a little bored right now so I'll raise the branches I have at the moment as normal github PRs, using this tool:
https://github.com/ejoffe/spr

When reviewing them, can you please avoid merging them, I want to see how effective the tool is at automatically merging them all.

**Comment by arduano** [comment]
Or I guess not. Apologies for the branch spam. There seems to be an authentication bug in that tool

I'll try to figure out another approach on the weekend. I know I can just squash everything into one larger PR, but it's interesting to find more flexible solutions to stack multiple PRs.

**Comment by arduano** [comment]
Anyway @urbas figured out I can use Facebook's tool called "sapling" to achieve similar results
https://sapling-scm.com/

Again, please avoid merging PRs yourself, I think it will break things, and lmn if the reviewing experience feels better with many PRs like this or not.

Apparently facebook's ReviewStack site makes it easier to review sapling PRs as well as you can jump up/down the PR stack.
https://reviewstack.dev/
