### ISSUE TITLE
Potential Project Partnership

### ISSUE THREAD

**Issue by kitcat86lasthuman** [urbas/rix#135]
Hi, I find your work to be excellent. I’d like to discuss an interesting opportunity. Can we connect? 

Telegram: @the_vereckel
Discord: vereckel
WhatsApp: +44 7341 822373

**Comment by arduano** [comment]
My preferred approach would be a discord group chat (discord: arduano). However, as @urbas is the owner of the project, I'll wait for his opinion.

**Comment by urbas** [comment]
This is unfortunately spam/scam.

**Comment by arduano** [comment]
Haven't seen this kind of spam on gh before honestly on my other OSS projects, but fair enough, they keep evolving ig
